# Generated by Django 2.0.5 on 2018-05-26 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('C_Reg_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('type_of_cmp', models.CharField(blank=True, choices=[('1', 'Sole Properitership'), ('2', 'Partnership'), ('3', 'Pvt ltd')], default=1, max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('ph_no', models.IntegerField(blank=True, null=True)),
                ('webLink', models.URLField(blank=True, null=True)),
                ('Linkdine', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('fb', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('C_Reg_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('type_of_company', models.CharField(blank=True, choices=[('1', 'Sole Properitership'), ('2', 'Partnership'), ('3', 'Pvt ltd')], default=1, max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('ph_no', models.IntegerField(blank=True, null=True)),
                ('webLink', models.URLField(blank=True, null=True)),
                ('Linkdine', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('fb', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, choices=[('1', 'Actively looking for job '), ('2', 'Service Notice period'), ('3', 'Looking for change'), ('4', 'Happy-but-want Onsite')], max_length=20, null=True)),
                ('Username', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('Designation', models.CharField(blank=True, max_length=20, null=True)),
                ('Skill', models.CharField(blank=True, max_length=20, null=True)),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('email1', models.EmailField(max_length=254)),
                ('Eemail2', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Whatsapp_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Category', models.CharField(blank=True, choices=[('1', 'Scholarship'), ('2', 'Admission'), ('3', 'Part time job'), ('4', 'Campus job'), ('5', 'Internship'), ('6', 'Summer job'), ('7', 'Work From Home')], default=1, max_length=20, null=True)),
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('Qualifications', models.CharField(blank=True, max_length=20, null=True)),
                ('Marks_percent', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
                ('Whatsapp_no', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Linkdin_profile', models.URLField(blank=True, null=True)),
                ('govt_id1', models.CharField(blank=True, max_length=20, null=True)),
                ('govt_id2', models.CharField(blank=True, max_length=20, null=True)),
                ('D_O_B', models.DateField(blank=True, null=True)),
                ('Home_pin', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
